import { type NextApiRequest, type NextApiResponse } from "next";
import { prisma } from "@/lib/prisma";
import { redis } from "@/lib/redis";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const { type, priority, title, body, metadata } = req.body;

    // Get a random user for load testing (in production this would be authenticated)
    const user = await prisma.user.findFirst({
      where: { role: "USER" },
      select: { id: true },
    });

    if (!user) {
      return res.status(400).json({ error: "No user found" });
    }

    // Create notification in database
    const notification = await prisma.notification.create({
      data: {
        userId: user.id,
        type: type || "SYSTEM",
        priority: priority || "NORMAL",
        title: title || "Load test notification",
        body: body || "Generated by k6 load test",
        metadata: metadata || {},
      },
    });

    // Publish to Redis for real-time delivery
    await redis.publish(
      `notifications:${user.id}`,
      JSON.stringify({
        ...notification,
        timestamp: new Date().toISOString(),
      })
    );

    // Invalidate unread cache
    await redis.del(`unread:${user.id}`);

    return res.status(201).json({
      id: notification.id,
      eventId: notification.id,
      timestamp: notification.createdAt,
    });
  } catch (error) {
    console.error("Event publish error:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
}
